name: API Tests

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        docker-compose up --build --abort-on-container-exit

    - name: Archive test reports
      if: always()  # Always try to upload, even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: results/

